config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :projects do
    resources :memberships
      resources :tasks do
        resources :comments
      end
  end

   root 'welcome#index'
   get 'faq' => 'common_questions#index'
   get 'about' => 'about#index'
   get 'terms' => 'terms#index'

   get '/signup' => 'registrations#new'
   post '/signup' => 'registrations#create'
   get '/signin' => 'authentication#new'
   post '/signin' => 'authentication#create'
   get '/signout' => 'authentication#destroy'

end

app/models/task.rb
class Task < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :users, through: :comments

  belongs_to :project
  validates :description, presence: true

end

app/controllers/tasks_controller.rb
class TasksController < MarketPagesController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate
  before_action :set_project, :except => [:index, :new, :create]


  def index
    @project = Project.find(params[:project_id])
    @tasks = @project.tasks
  end

  def show
    @project = Project.find(params[:project_id])
    @task = Task.find(params[:id])
    @comment = Comment.new
  end

  def new
    @project = Project.find(params[:project_id])
    @task = Task.new
  end

  def edit
    @task.project_id = params[:project_id]
    @project = Project.find(params[:project_id])
  end

  def create
    @project = Project.find(params[:project_id])
    @task = Task.new(task_params)
    @task.project_id = @project.id
      if @task.save
      redirect_to project_tasks_path(@project), notice: 'Task was successfully created.'
      else
        render :new
      end
    end

  def update
    @task.project_id = params[:project_id]
    @project = Project.find(params[:project_id])

    if @task.update(task_params)
      redirect_to project_path(@task.project_id), notice: "Task was successfully updated!"
    else
      render :edit
  end
  end

  def destroy
    @project = Project.find(params[:project_id])
    @task.project_id = params[:project_id]
    @task.destroy
      redirect_to project_tasks_path(@project), notice: 'Task was successfully destroyed.'
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
      unless @project && @project.users.include?(current_user) || current_user.admin?
        redirect_to projects_path, notice: 'You do not have access to that project.'
      end
     end

    def task_params
      params.require(:task).permit(:description, :date, :complete, :project_id)
    end
end

app/views/tasks/_comment.html.erb
<%= form_for [@project, @task, @comment], html: {class: "form-horizontal"} do |f| %>

  <div class="form-group">
    <div class= "col-md-9">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-4">
      <div class="action">
        <%= f.submit "Add Comment", class: "btn btn-primary" %>
      </div>
    </div>
    <% end %>
  </div>

app/views/tasks/_form.html.erb
<%= form_for [@project, @task], html: {class: "form-horizontal"} do |f| %>

<%= render partial: 'shared/error', locals: { object: @task } %>

<div class="form-group">
  <div class = "field">
    <div class = "control-label col-md-2">
      <%= f.label :description %>
    </div>
  </div>
  <div class= "col-md-4">
    <%= f.text_field :description, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <div class = "field">
    <div class = "control-label col-md-2">
      <%= f.label :due_date %>
    </div>
  </div>
  <div class= "col-md-4">
    <%= f.date_select :date, class: "form-control" %>
  </div>
</div>

<% if @task.description != nil %>

<div class="form-group">
  <div class = "field">
    <div class = "control-label col-md-2">
      <%= f.label :completed %>
    </div>
    <%= f.check_box :complete %>
  </div>
  <div class= "col-md-4">

  </div>
</div>
<% end %>

<div class="form-group">
  <div class="col-md-4 col-md-offset-2">
    <div class="action">
      <%= f.submit class: "btn btn-primary" %>
      <a class= "btn btn-default" href= "/tasks">Cancel</a>
    </div>
  </div>
</div>




<% end %>

app/views/tasks/edit.html.erb
<div class="container">

  <div class="page-header">
<h1>Editing Task</h1>
  </div>

  <ol class="breadcrumb">
    <li><%= link_to "Tasks", project_tasks_path(@project) %></li>
    <li class="active"><%= @task.description %></li>
  </ol>

  <%= render 'form' %>

</div>

app/views/tasks/index.html.erb
<div class="container">
  <div class="page-header">

    <% if notice %>
    <div class= "alert alert-success"><%= notice %></div>
    <% end %>

    <div class="pull-right"><%= link_to 'New Task', new_project_task_path(@project), class: "btn btn-info" %>
    </div>
    <h1><%="#{"Tasks for "}#{@project.name}"%></h1>
  </div>

  <ol class="breadcrumb">
    <li><a href="/projects">Projects</a></li>
    <li><%= link_to @project.name, project_path(@project), id: "pro-name" %></li>
    <li class="active">Tasks</li>
  </ol>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Description</th>
        <th>Due Date</th>
        <th>Complete</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to task.description + " ", project_task_path(@project, task),
                id: "task-desc" %><p class="badge"><%= task.comments.count %></p></td>
        <td><%= task.date %></td>
        <td><%= task.complete %></td>
        <td class ="text-right"><%= link_to 'Edit', edit_project_task_path(@project, task),
                    class: "btn btn-info" %>
          <%= link_to '<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>'.html_safe,
              project_task_path(@project, task), id: "destroy", method: :delete, data:
              { confirm: "Are you sure you want to delete this?" } %></td>
          <br>
        </tr>
        <% end %>
      </tbody>
    </table>

    <br>

app/views/tasks/new.html.erb
<div class="page-header">
  <h1>New Task</h1>
</div>

<ol class="breadcrumb">
  <li><%= link_to "Tasks", project_tasks_path(@project) %></li>
  <li><%= @project.name %></li>
  <li class="active">New Task</li>
</ol>


<%= render 'form' %>

app/views/tasks/show.html.erb
<div class="page-header">
  <% if notice %>
  <div class= "alert alert-success"><%= notice %></div>
  <% end %>


  <div class="pull-right">
    <%= link_to "Edit", edit_project_task_path(@project, @task), class: "btn btn-info" %></div>
    <h1><%= @task.description %></h1>
  </div>


  <ol class="breadcrumb">
    <li><%= link_to @project.name, project_path(@project) %></li>
    <li><%= link_to "Tasks", project_tasks_path(@project) %></a></li>
    <li class="active"><%= @task.description %></li>
  </ol>

  <p><strong> Due on: </strong><%= @task.date %></p>

  <h3>Comments</h3>

    <% @task.comments.each do |comment| %>
      <div class="row">
        <div class="col-md-3">
          <% if comment.user_id? %>
          <p><%= link_to comment.user.full_name, user_path(comment.user_id) %></p>
          <p class="text-muted"><%= time_ago_in_words(comment.created_at) %> ago</p>
        </div>
        <% else %>
        <p><%= "Deleted User" %></p>
        <p class="text-muted"><%= time_ago_in_words(comment.created_at) %></p>
        <% end %>
          <p class="col-md-9"><%= comment.description %></p>
      </div>
      <% end %>


  <%= render 'comment' %>