config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :projects do
    resources :memberships
      resources :tasks do
        resources :comments
      end
  end

   root 'welcome#index'
   get 'faq' => 'common_questions#index'
   get 'about' => 'about#index'
   get 'terms' => 'terms#index'

   get '/signup' => 'registrations#new'
   post '/signup' => 'registrations#create'
   get '/signin' => 'authentication#new'
   post '/signin' => 'authentication#create'
   get '/signout' => 'authentication#destroy'

end

app/models/project.rb
class Project < ActiveRecord::Base
 has_many :memberships, dependent: :destroy
 has_many :users, through: :memberships

 has_many :tasks, dependent: :destroy
 validates :name, presence: true

end

app/controllers/projects_controller.rb
class ProjectsController < MarketPagesController
  before_action :authenticate
  before_action :set_project, :except => [:index, :new, :create]
  before_action :set_owner, :only => [:update, :edit]


  def index
    if current_user.admin?
      @projects = Project.all
    else
      @projects = current_user.projects
  end
end

  def new
    @project = Project.new
  end

  def edit
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      @membership = Membership.create(user_id: current_user.id, project_id: @project.id, role: 1)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      @project.memberships.create(role: 1, user_id: current_user.id)
      redirect_to project_tasks_path(@project), notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  def show
    @project =Project.find(params[:id])
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to @project, notice: 'Project was successfully deleted.'
  end

  private

  def set_project
    if @project && @project.users.include?(current_user)
      redirect_to projects_path, notice: 'You do not have access to that project.'
    end
   end

  def set_owner
    @project = Project.find(params[:id])
    unless current_user.owns_project?(@project)
      redirect_to project_path(@project), notice: 'You do not have access.'
    end
  end

  def project_params
    params.require(:project).permit(:name)
  end

end

app/views/projects/_form.html.erb
<%= form_for(@project, html: {class: "form-horizontal"}) do |f| %>
<%= render partial: 'shared/error', locals: { object: @project } %>


<div class="form-group">
  <div class = "field">
    <div class = "control-label col-md-2">
      <%= f.label :name %>
    </div>
  </div>
  <div class= "col-md-4">
    <%= f.text_field :name, class: "form-control" %>
  </div>
</div>


<div class="form-group">
  <div class="col-md-4 col-md-offset-2">
    <div class="action">
      <%= f.submit class: "btn btn-primary" %>
      <a class= "btn btn-default" href= "/tasks">Cancel</a>
    </div>
  </div>
</div>





<% end %>

app/views/projects/edit.html.erb
<div class="container">

  <div class="page-header">
    <h1>Edit Project</h1>
  </div>


  <%= render 'form' %>

app/views/projects/index.html.erb
<div class="container">
  <div class="page-header">

    <% if notice %>
    <div class= "alert alert-success"><%= notice %></div>
    <% end %>

    <div class="pull-right"><%= link_to 'New Project', new_project_path, id: "new-pro", class: "btn btn-info" %>
    </div>
    <h1>Projects</h1>
  </div>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Tasks</th>
      </tr>
    </thead>

    <tbody>
      <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project %></td>
        <td><%= link_to project.tasks.count, project_tasks_path(project) %></td>
        <% end %>
      </tbody>
    </table>

    <br>

app/views/projects/new.html.erb
<div class="page-header">
  <h1>Create Project</h1>
</div>



<%= render 'form' %>

app/views/projects/show.html.erb
<div class="page-header">
  <% if notice %>
  <div class= "alert alert-success"><%= notice %></div>
  <% end %>

    <div class="pull-right">
      <% if current_user.owns_project?(@project) || current_user.admin? %>
        <%= link_to 'Edit', edit_project_path, class: "btn btn-info" %></td>
      <% end %>
    </div>

      <h1><%= @project.name %></h1>
    </div>

    <ol class="breadcrumb">
      <li><a href="/projects">Projects</a></li>
      <li class="active"><%= @project.name %></li>
    </ol>

<p><%= link_to "#{@project.tasks.count}#{" Tasks"}", project_tasks_path(@project) %></p>
<p><%= link_to "#{@project.memberships.count}#{" Members"}", project_memberships_path(@project) %></p>

<% if current_user.owns_project?(@project) || current_user.admin? %>
  <div class="well">
    <h4>Delete</h4>
    <p><%= "Deleting this project will also delete #{@project.memberships.count}
          #{" memberships, "} #{@project.tasks.count}#{" tasks"} and associated comments."%></p>
    <%= link_to 'Delete', @project, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
  <% end %>