config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :projects do
    resources :memberships
      resources :tasks do
        resources :comments
      end
  end

   root 'welcome#index'
   get 'faq' => 'common_questions#index'
   get 'about' => 'about#index'
   get 'terms' => 'terms#index'

   get '/signup' => 'registrations#new'
   post '/signup' => 'registrations#create'
   get '/signin' => 'authentication#new'
   post '/signin' => 'authentication#create'
   get '/signout' => 'authentication#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>taskr-Alexandra</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>


  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">

        <a class="navbar-brand" href="/">taskr</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
            <li><%= link_to "#{current_user.full_name}", user_path(current_user) %></li>
            <li><%= link_to 'Sign Out', signout_path %></li>
            <% else %>
            <li><%= link_to 'Signup', signup_path %></li>
            <li><%= link_to 'Signin', signin_path %></li>
            <% end %>
          </ul>

        </div><!--/.navbar-collapse -->
      </div>
      </div>

  </nav>


  <div class= "container">

      <%= yield %>

      <hr>

      <footer>
        <div class="row">
          <div class="col-md-6">
            <%= link_to "About", about_path %>
            |
            <%= link_to "Terms", terms_path %>
            |
            <%= link_to "FAQ", faq_path %>
            |
            <%= link_to "Users", users_path %>
            |
            <%= link_to "Projects", projects_path %>
          </div>


          <div class="col-md-6 text-right">
            <a href="https://www.linkedin.com">
              <%= image_tag("linkedin.jpg", class: "img-footer") %>
            </a>
            <a href="https://github.com/">
              <%= image_tag("git.jpg", class: "img-footer") %>
            </a>
            <a href="https://twitter.com/">
              <%= image_tag("twitter.jpg", class: "img-footer") %>
            </a>
            <a href="https://students.gschool.it/">
              <%= image_tag("gschool.jpg", class: "img-footer") %>
            </a>
          </div>
        </div>
      </footer>
  </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>


  </body>
</html>

app/views/layouts/market_pages.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>taskr-Alexandra</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>


  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">

        <a class="navbar-brand" href="/projects">taskr</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">

          <% if current_user %>
              <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Projects <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                    <% Membership.all.each do |membership| %>
                    <% if membership.user_id == current_user.id %>
                  <li><%= link_to membership.project.name, project_path(membership.project) %></li>
                    <% end %>
                    <% end %>
                  <li class="divider">
                  </li>
                    <li>
                      <%= link_to 'New Project', new_project_path %>
                    </li>
                </ul>
              </li>
              <li>
                <%= link_to 'Users', users_path %>
              </li>
            </ul>



            <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "#{current_user.full_name}", user_path(current_user) %></li>
            <li><%= link_to 'Sign Out', signout_path %></li>
            <% else %>
            <li><%= link_to 'Signup', signup_path %></li>
            <li><%= link_to 'Signin', signin_path %></li>
            <% end %>


          </ul>

        </div>
      </div>
      </div>

  </nav>


  <div class= "container">

      <%= yield %>

      <hr>

      <footer>
        <div class="row">
          <div class="text-center">
            <%= link_to "Home", root_path %>
            |
            <%= link_to "About", about_path %>
            |
            <%= link_to "Terms", terms_path %>
            |
            <%= link_to "FAQ", faq_path %>
          </div>
        </div>
      </footer>
  </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>


  </body>
</html>